db:
  driver:   postgres
  host:     localhost
  port:     5432
  database: fern
  username: fern
  password: fern
  detail-log:     true
  max-open-conns: 100
  max-idle-conns: 10
server:
  port: :8080
auth:
  json-web-keys-endpoint: "https://guidewire-hub.oktapreview.com/oauth2/ausj9ftnbxOqfGU4U0h7/v1/keys"
  enabled: "false"
  scope-claim-name: "scope"
header: "Fern Acceptance Test Report"